version: 0.2

env:
  variables:
    NODE_ENV: 'production'

# proxy:
#   upload-artifacts: yes
#   logs: yes

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt-get update
      - npm ci
      - npx lerna bootstrap --ci
  # pre_build:
  #   commands:
  #     - npm install
  #     - npx lerna bootstrap
  build:
    commands:
      - ls node_modules/.bin
      - npm rebuild
      - ls node_modules/.bin
      - npm run build
  # post_build:
  #   run-as: Linux-user-name
  #   commands:
  #     - command
  #     - command
  #   finally:
  #     - command
  #     - command
artifacts:
  files:
    - ./webapp/dist/**/*
    - ./api/build/**/*
  name: syncify-artifact
  # discard-paths: yes
  base-directory: ./
  # secondary-artifacts:
  #   artifactIdentifier:
  #     files:
  #       - location
  #       - location
  #     name: secondary-artifact-name
  #     discard-paths: yes
  #     base-directory: location
  #   artifactIdentifier:
  #     files:
  #       - location
  #       - location
  #     discard-paths: yes
  #     base-directory: location
# cache:
#   paths:
#     - node_modules
#     - ./api/node_modules
#     - ./webapp/node_modules
