service: syncify
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  # 'dev' locally, 'prod' when deployed with serverless --stage prod
  stage: ${opt:stage, 'dev'}

functions:
  room:
    handler: ./src/api/modules/rooms/handlers/show.handler
    name: ${self:provider.stage}-room
    environment:
      ROOMS_TABLE_NAME: ${self:provider.stage}-rooms
    events:
      - http:
          path: api/rooms/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

  authorizationTradeToken:
    handler: ./src/api/modules/auth/handlers/trade-token.handler
    environment:
      USERS_TABLE_NAME: ${self:provider.stage}-users
      SPOTIFY_CLIENT_ID: ${env:SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${env:SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URL: ${env:SPOTIFY_REDIRECT_URL}
    events:
      - http:
          path: api/auth/trade-token
          method: post

  authorizationRefresh:
    handler: ./src/api/modules/auth/handlers/refresh.handler
    environment:
      USERS_TABLE_NAME: ${self:provider.stage}-users
      SPOTIFY_CLIENT_ID: ${env:SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${env:SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URL: ${env:SPOTIFY_REDIRECT_URL}
    events:
      - http:
          path: api/auth/refresh
          method: post

resources:
  - Conditions:
      CreateProdResources:
        Fn::Equals:
          - ${self:provider.stage}
          - prod
  - ${file(infrastructure/cloudfront.yml)}
  - Resources:
      AssetsBucket:
        Type: AWS::S3::Bucket
        Condition: CreateProdResources
        Properties:
          BucketName: syncify-assets
          AccessControl: PublicRead
      UsersTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ${self:provider.stage}-users
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          BillingMode: PAY_PER_REQUEST
      RoomsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ${self:provider.stage}-rooms
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          BillingMode: PAY_PER_REQUEST
