apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: syncify
spec:
  selector:
    matchLabels:
      app: syncify
      tier: api
  replicas: 1
  template:
    metadata:
      labels:
        app: syncify
        tier: api
    spec:
      containers:
        - name: api
          image: repo.treescale.com/liachthuaber/syncify-api:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: syncify
    tier: api
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: syncify
    tier: frontend
