apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: syncify
spec:
  selector:
    matchLabels:
      app: syncify
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: syncify
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: repo.treescale.com/liachthuaber/syncify-frontend:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: syncify
    tier: frontend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
    - port: 80
  selector:
    app: syncify
    tier: frontend
