Resources:
  Cloudfront:
    Type: AWS::CloudFront::Distribution
    Condition: CreateProdResources
    Properties:
      DistributionConfig:
        Aliases: [syncify.xyz]
        Comment: Syncify CDN and reverse proxy
        DefaultCacheBehavior:
          Compress: true
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          TargetOriginId: assets-bucket
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - Id: assets-bucket
            DomainName: !GetAtt AssetsBucket.DomainName
            S3OriginConfig:
              # TODO: access to bucket only through cloudfront
              OriginAccessIdentity: ''
        PriceClass: PriceClass_100
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: index.html
        ViewerCertificate:
          # Hardcoded certificate
          AcmCertificateArn: arn:aws:acm:us-east-1:394586955256:certificate/59854e5b-0ee7-4867-9024-81e02442f612
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
