Resources:
  Cloudfront:
    Type: AWS::CloudFront::Distribution
    Condition: CreateProdResources
    Properties:
      DistributionConfig:
        Aliases: [syncify.co]
        Comment: Syncify CDN and reverse proxy
        CustomErrorResponses:
          # redirect 404 and 403 responses from s3 to single page app
          - ErrorCachingMinTTL: 60
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCachingMinTTL: 60
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          Compress: true
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          TargetOriginId: assets-bucket
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          - PathPattern: /graphql
            Compress: true
            AllowedMethods: [HEAD, DELETE, POST, GET, OPTIONS, PUT, PATCH]
            DefaultTTL: 60
            ForwardedValues:
              Cookies:
                Forward: all
              QueryString: false
            TargetOriginId: graphql-api
            ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - DomainName: !GetAtt AssetsBucket.DomainName
            Id: assets-bucket
            S3OriginConfig:
              # TODO: access to bucket only through cloudfront
              OriginAccessIdentity: ''
          - DomainName: !GetAtt BeanstalkEnvironmentProd.EndpointURL
            Id: graphql-api
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        PriceClass: PriceClass_100
        ViewerCertificate:
          # Hardcoded certificate
          AcmCertificateArn: arn:aws:acm:us-east-1:394586955256:certificate/a34d2c76-3c76-448c-9b1c-ee924e509240
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
