Resources:
  Cloudfront:
    Type: AWS::CloudFront::Distribution
    Condition: CreateProdResources
    Properties:
      DistributionConfig:
        Aliases: [syncify.co]
        Comment: Syncify CDN and reverse proxy
        DefaultCacheBehavior:
          Compress: true
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          TargetOriginId: assets-bucket
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - Id: assets-bucket
            DomainName: !GetAtt AssetsBucket.DomainName
            S3OriginConfig:
              # TODO: access to bucket only through cloudfront
              OriginAccessIdentity: ''
        PriceClass: PriceClass_100
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        ViewerCertificate:
          # Hardcoded certificate
          AcmCertificateArn: arn:aws:acm:us-east-1:394586955256:certificate/a34d2c76-3c76-448c-9b1c-ee924e509240
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
  WebappDns:
    Type: AWS::Route53::RecordSet
    Properties:
      Type: A
      Name: syncify.co.
      HostedZoneName: syncify.co.
      AliasTarget:
        DNSName: !GetAtt Cloudfront.DomainName
        # `Z2FDTNDATAQYW2` is AWS magic constant that is the same for all cloudfront recordsets
        HostedZoneId: Z2FDTNDATAQYW2
