service: syncify
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: dev
  profile: dev

custom:
  # 'dev' locally, 'prod' when deployed with serverless --stage prod
  stage: ${opt:stage, self:provider.stage}

resources:
  - Conditions:
      CreateProdResources:
        Fn::Equals:
          - ${opt:stage, ''}
          - prod
  - ${file(infrastructure/cloudfront.yml)}
  - ${file(infrastructure/beanstalk-app.yml)}
  - Resources:
      # DynamoDB Table: Rooms
      AssetsBucket:
        Type: AWS::S3::Bucket
        Condition: CreateProdResources
        Properties:
          BucketName: syncify-assets
          AccessControl: PublicRead
      ArtifactsBucket:
        Type: AWS::S3::Bucket
        Condition: CreateProdResources
        Properties:
          BucketName: syncify-artifacts
      UsersTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: ${self:custom.stage}-users
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          BillingMode: PAY_PER_REQUEST
