name: Build Artifacts

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Setting up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: ls
      - run: node --version
      - name: Install dependencies
        run: npm ci --prefer-offline && npx lerna bootstrap --ci
      - name: Build
        run: npm run build
      - name: Typecheck
        run: npm run typecheck
      # - name: Test
      #   run: npm run test
      - name: Lint
        run: npm run lint
